# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-01-24 22:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('subscription', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='currency',
            field=models.CharField(default=b'USD', max_length=3),
        ),
    ]
